use_frameworks!

platform :ios, '8.0'

target 'renRenTest_Example' do
  pod 'renRenTest', :path => '../'

  target 'renRenTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
